// src/components/Component1722.vue
<template>
  <a href="https://docs.chocofinance.com/">
    <div class="component-17-2-14">
      <div class="documentation-29 montserrat-semi-bold-white-9px">{{ documentation }}</div>
    </div></a
  >
</template>

<script>
export default {
  name: "Component1722",
  props: ["documentation"],
};
</script>

<style lang="sass">
.component-17-2-14
  cursor: pointer
  display: flex
  height: 12px
  left: 0
  position: absolute
  top: 0
  transition: all 0.2s ease
  width: 93px

.component-17-2-14:hover
  opacity: 0

.documentation-29
  flex: 1
  letter-spacing: 0
  line-height: 9px
  margin-bottom: -2.1px
  margin-right: 6.3px
  margin-top: 1px
  white-space: nowrap
  width: 87px
</style>

// components/Component1722/index.jsx
import React from "react";
import "./Component1722.css";

class Component1722 extends React.Component {
  render() {
    const { children } = this.props;

    return (
      <a href="https://docs.chocofinance.com/">
        <div className="component-17-2-14">
          <div className="documentation-29 montserrat-semi-bold-white-9px">{children}</div>
        </div>
      </a>
    );
  }
}

export default Component1722;
