// src/components/Component1912.vue
<template>
  <div class="component-19-2">
    <div class="join-choco-discord-12 montserrat-semi-bold-white-20px">{{ children }}</div>
  </div>
</template>

<script>
export default {
  name: "Component1912",
  props: ["children"],
};
</script>

<style lang="sass">
.component-19-2,
.component-19-2-1,
.component-19-2-2,
.component-19-2-3,
.component-19-2-4,
.component-19-2-5,
.component-19-2-6,
.component-19-2-7,
.component-19-2-8,
.component-19-2-9,
.component-19-2-10,
.component-19-2-11
  cursor: pointer
  display: flex
  height: 24px
  left: 0
  position: absolute
  top: 0
  transition: all 0.2s ease
  width: 239px

.component-19-2:hover,
.component-19-2-1:hover,
.component-19-2-2:hover,
.component-19-2-3:hover,
.component-19-2-4:hover,
.component-19-2-5:hover,
.component-19-2-6:hover,
.component-19-2-7:hover,
.component-19-2-8:hover,
.component-19-2-9:hover,
.component-19-2-10:hover,
.component-19-2-11:hover
  opacity: 0

.join-choco-discord-12,
.join-choco-discord-13,
.join-choco-discord-14,
.join-choco-discord-15,
.join-choco-discord-16,
.join-choco-discord-17,
.join-choco-discord-18,
.join-choco-discord-19,
.join-choco-discord-20,
.join-choco-discord-21,
.join-choco-discord-22,
.join-choco-discord-23
  flex: 1
  letter-spacing: 0
  line-height: 20px
  margin-bottom: -4px
  margin-right: -2px
  margin-top: 2px
  white-space: nowrap
  width: 239px
</style>

// components/Component1912/index.jsx
import React from "react";
import "./Component1912.sass";

class Component1912 extends React.Component {
  render() {
    const { children } = this.props;

    return (
      <div className="component-19-2">
        <div className="join-choco-discord-1 montserrat-semi-bold-white-20px">{children}</div>
      </div>
    );
  }
}

export default Component1912;
