// src/components/Component211.vue
<template>
  <div class="component-21-1">
    <component121 :x622369b7e403e7ddc4ce09396Props="component121Props.x622369b7e403e7ddc4ce09396Props" />
    <component131
      :className="component131Props.className"
      :component1511Props="component131Props.component1511Props"
      :component1512Props="component131Props.component1512Props"
      :component152Props="component131Props.component152Props"
      :component1513Props="component131Props.component1513Props"
    />
    <component141
      :className="component141Props.className"
      :component171Props="component141Props.component171Props"
      :component181Props="component141Props.component181Props"
      :component18122Props="component141Props.component18122Props"
    />
    <component157
      :className="component157Props.className"
      :component191Props="component157Props.component191Props"
      :component1912Props="component157Props.component1912Props"
    />
  </div>
</template>

<script>
import Component121 from "./Component121";
import Component131 from "./Component131";
import Component141 from "./Component141";
import Component157 from "./Component157";
export default {
  name: "Component211",
  components: {
    Component121,
    Component131,
    Component141,
    Component157,
  },
  props: ["component121Props", "component131Props", "component141Props", "component157Props"],
};
</script>

<style lang="sass">
.component-21-1,
.component-21-1-1
  align-items: flex-start
  display: flex
  height: 249px
  left: 68px
  min-width: 950px
  position: absolute
  top: 116px
</style>

// components/Component211/index.jsx
import React from "react";
import Component121 from "../Component121";
import Component131 from "../Component131";
import Component141 from "../Component141";
import Component157 from "../Component157";
import "./Component211.css";

class Component211 extends React.Component {
  render() {
    const { component121Props, component131Props, component141Props, component157Props } = this.props;

    return (
      <div className="component-21-1">
        <Component121 x622369b7e403e7ddc4ce09396Props={component121Props.x622369b7e403e7ddc4ce09396Props} />
        <Component131
          className={component131Props.className}
          component1511Props={component131Props.component1511Props}
          component1512Props={component131Props.component1512Props}
          component152Props={component131Props.component152Props}
          component1513Props={component131Props.component1513Props}
        />
        <Component141
          className={component141Props.className}
          component171Props={component141Props.component171Props}
          component181Props={component141Props.component181Props}
          component18122Props={component141Props.component18122Props}
        />
        <Component157
          className={component157Props.className}
          component191Props={component157Props.component191Props}
          component1912Props={component157Props.component1912Props}
        />
      </div>
    );
  }
}

export default Component211;
