// components/Component171/index.jsx
import React from "react";
import "./Component171.sass";

class Component171 extends React.Component {
  render() {
    const { children } = this.props;

    return (
      <div className="component-17-1">
        <div className="documentation montserrat-semi-bold-celeste-20px">{children}</div>
      </div>
    );
  }
}

export default Component171;

// src/components/Component171.vue
<template>
  <div class="component-17-1">
    <div class="documentation montserrat-semi-bold-celeste-20px">{{ children }}</div>
  </div>
</template>

<script>
export default {
  name: "Component171",
  props: ["children"],
};
</script>

<style lang="sass">
.component-17-1,
.component-17-1-1,
.component-17-1-2,
.component-17-1-3,
.component-17-1-4,
.component-17-1-5,
.component-17-1-6,
.component-17-1-7,
.component-17-1-8,
.component-17-1-9,
.component-17-1-10,
.component-17-1-11,
.component-17-1-12,
.component-17-1-13
  display: flex
  height: 24px
  left: 0
  position: absolute
  top: 0
  width: 191px

.documentation,
.documentation-1,
.documentation-2,
.documentation-3,
.documentation-4,
.documentation-5,
.documentation-6,
.documentation-7,
.documentation-8,
.documentation-9,
.documentation-10,
.documentation-11,
.documentation-12,
.documentation-13
  flex: 1
  letter-spacing: 0
  line-height: 20px
  margin-bottom: -4px
  margin-right: -2px
  margin-top: 2px
  white-space: nowrap
  width: 191px
</style>
