// components/Component191/index.jsx
import React from "react";
import "./Component191.sass";

class Component191 extends React.Component {
  render() {
    const { children } = this.props;

    return (
      <div className="component-19-1">
        <div className="join-choco-discord montserrat-semi-bold-celeste-20px">{children}</div>
      </div>
    );
  }
}

export default Component191;

// src/components/Component191.vue
<template>
  <div class="component-19-1">
    <div class="join-choco-discord montserrat-semi-bold-celeste-20px">{{ children }}</div>
  </div>
</template>

<script>
export default {
  name: "Component191",
  props: ["children"],
};
</script>

<style lang="sass">
.component-19-1,
.component-19-1-1,
.component-19-1-2,
.component-19-1-3,
.component-19-1-4,
.component-19-1-5,
.component-19-1-6,
.component-19-1-7,
.component-19-1-8,
.component-19-1-9,
.component-19-1-10,
.component-19-1-11
  cursor: pointer
  display: flex
  height: 24px
  left: 0
  position: absolute
  top: 0
  transition: all 0.2s ease
  width: 239px

.component-19-1:hover,
.component-19-1-1:hover,
.component-19-1-2:hover,
.component-19-1-3:hover,
.component-19-1-4:hover,
.component-19-1-5:hover,
.component-19-1-6:hover,
.component-19-1-7:hover,
.component-19-1-8:hover,
.component-19-1-9:hover,
.component-19-1-10:hover,
.component-19-1-11:hover
  opacity: 0

.join-choco-discord,
.join-choco-discord-1,
.join-choco-discord-2,
.join-choco-discord-3,
.join-choco-discord-4,
.join-choco-discord-5,
.join-choco-discord-6,
.join-choco-discord-7,
.join-choco-discord-8,
.join-choco-discord-9,
.join-choco-discord-10,
.join-choco-discord-11
  flex: 1
  letter-spacing: 0
  line-height: 20px
  margin-bottom: -4px
  margin-right: -2px
  margin-top: 2px
  white-space: nowrap
  width: 239px
</style>
