// components/Component172/index.jsx
import React from "react";
import "./Component172.css";

class Component172 extends React.Component {
  render() {
    return (
      <a href="https://docs.chocofinance.com/">
        <div className="component-17-2">
          <div className="documentation-14 montserrat-semi-bold-white-20px">DOCUMENTATION</div>
        </div>
      </a>
    );
  }
}

export default Component172;

// src/components/Component172.vue
<template>
  <a href="https://docs.chocofinance.com/">
    <div class="component-17-2">
      <div class="documentation-14 montserrat-semi-bold-white-20px">DOCUMENTATION</div>
    </div></a
  >
</template>

<script>
export default {
  name: "Component172",
};
</script>

<style lang="sass">
.component-17-2,
.component-17-2-1,
.component-17-2-2,
.component-17-2-3,
.component-17-2-4,
.component-17-2-5,
.component-17-2-6,
.component-17-2-7,
.component-17-2-8,
.component-17-2-9,
.component-17-2-10,
.component-17-2-11,
.component-17-2-12,
.component-17-2-13
  cursor: pointer
  display: flex
  height: 24px
  left: 0
  position: absolute
  top: 0
  transition: all 0.2s ease
  width: 191px

.component-17-2:hover,
.component-17-2-1:hover,
.component-17-2-2:hover,
.component-17-2-3:hover,
.component-17-2-4:hover,
.component-17-2-5:hover,
.component-17-2-6:hover,
.component-17-2-7:hover,
.component-17-2-8:hover,
.component-17-2-9:hover,
.component-17-2-10:hover,
.component-17-2-11:hover,
.component-17-2-12:hover,
.component-17-2-13:hover
  opacity: 0

.documentation-14,
.documentation-15,
.documentation-16,
.documentation-17,
.documentation-18,
.documentation-19,
.documentation-20,
.documentation-21,
.documentation-22,
.documentation-23,
.documentation-24,
.documentation-25,
.documentation-26,
.documentation-27
  flex: 1
  letter-spacing: 0
  line-height: 20px
  margin-bottom: -4px
  margin-right: -2px
  margin-top: 2px
  white-space: nowrap
  width: 191px
</style>
