// src/components/Component1712.vue
<template>
  <div class="component-17-1-14">
    <div class="documentation-28 montserrat-semi-bold-celeste-9px">{{ children }}</div>
  </div>
</template>

<script>
export default {
  name: "Component1712",
  props: ["children"],
};
</script>

<style lang="sass">
.component-17-1-14
  display: flex
  height: 12px
  left: 0
  position: absolute
  top: 0
  width: 93px

.documentation-28
  flex: 1
  letter-spacing: 0
  line-height: 9px
  margin-bottom: -2.1px
  margin-right: 6.3px
  margin-top: 1px
  white-space: nowrap
  width: 87px
</style>

// components/Component1712/index.jsx
import React from "react";
import "./Component1712.sass";

class Component1712 extends React.Component {
  render() {
    const { children } = this.props;

    return (
      <a href="https://docs.chocofinance.com/">
        <div className="component-17-2">
          <div className="documentation-1 montserrat-semi-bold-white-20px">{children}</div>
        </div>
      </a>
    );
  }
}

export default Component1712;
